In [2]:
import string
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
from keras.utils import to_categorical
from keras import Sequential
from keras.layers import Dense, LSTM, Embedding
import pickle
import pandas as pd

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Couldn't import dot_parser, loading of dot files will not be possible.


In [3]:
df = pd.read_csv('all_songs.csv')

In [4]:
lyrics = df.loc[df['album'] == 'In the Aeroplane Over the Sea']['lyrics'].values

In [37]:
for lyric in lyrics[:2]:
    text = (lyric.lower().replace(' n ', ' eol ').replace('[verse ', '[verse'))
    text = text.replace("'", '').replace('-', ' ')
    tokens = text.split()
    table = str.maketrans('', '', string.punctuation)
    tokens = [w.translate(table) for w in tokens]

In [5]:
def load_data(filename='all_songs.csv',
              col='album',
              col_value='In the Aeroplane Over the Sea'):
    
    df    = pd.read_csv('all_songs.csv')
    df    = df.loc[df[col] == col_value]
    songs = df['lyrics'].values
    return songs

In [6]:
def lyric_cleaner(songs):
    lyric_tokens = []
    for song in songs:
        text = song.lower().replace(' n ', ' eol ').replace('[verse ', '[verse')
        text = text.replace("'", '').replace('-', ' ')
        tokens = text.split()
        table = str.maketrans('', '', string.punctuation)
        tokens = [word.translate(table) for word in tokens]
        lyric_tokens.append(tokens)
    
    return lyric_tokens

In [7]:
for i in lyric_tokens[:1]:
    print(i)

NameError: name 'lyric_tokens' is not defined

In [8]:
def join_song_lyrics(lyric_tokens):
    
    joined_songs = []
    
    for song in lyric_tokens:
        lyrics = ' '.join(song)
        joined_songs.append(lyrics)
        
    return joined_songs

In [9]:
def tokenizer(list_of_songs, tokenizer=Tokenizer()):
    tokenizer = tokenizer
    tokenizer.fit_on_texts(list_of_songs)
    encoded_songs = tokenizer.texts_to_sequences(list_of_songs)
    
    return encoded_songs, tokenizer

In [10]:
def find_longest_song(encoded_songs):
    longest_song_size = 0
    for song in encoded_songs:
        if len(song) > longest_song_size:
            longest_song_size = len(song)
    return longest_song_size

In [11]:
def index_to_word(tokenizer):
    vocab_size = len(tokenizer.word_index) + 1
    index_to_word_dict =  dict([(index, word) for word, index in tokenizer.word_index.items()])
    return vocab_size, index_to_word_dict

In [12]:
pad_sequences(encoded_songs, maxlen=longest_song_size, padding='post', truncating='post')

NameError: name 'encoded_songs' is not defined

In [13]:
def pad_data(encoded_songs, max_length):
    padded_songs = pad_sequences(encoded_songs, maxlen=max_length, padding='post', truncating='post')
    return padded_songs

In [44]:
def seqeuncer(padded_songs, length=seq_length):
    sequences = []
    output = []

    for song in padded_songs:
        for i in range(length, (len(song))):
            seq = song[i - length: i]
            out = song[i]
            sequences.append(seq)
            output.append(out)
            
    return np.array(sequences), output

In [ ]:
def ltsm_model():
    

In [61]:
seq_length = 10

data = load_data()

lyric_tokens = lyric_cleaner(data)

list_of_songs = join_song_lyrics(lyric_tokens)

encoded_songs, toke = tokenizer(list_of_songs=list_of_songs)

vocab_size, reverse_dict = index_to_word(tokenizer=toke)

longest_song_size = find_longest_song(encoded_songs=encoded_songs)

padded_songs = pad_data(encoded_songs, max_length=longest_song_size)

X, y = seqeuncer(padded_songs=padded_songs, length=seq_length)

y = to_categorical(y)

In [60]:
to_categorical(y).shape

(11902, 643)

In [43]:
seqeuncer(padded_songs=padded_songs, length=seq_length)

10 17
11 292
12 133
13 1
14 2
15 37
16 6
17 293
18 13
19 294
20 295
21 42
22 3
23 134
24 1
25 7
26 94
27 296
28 14
29 135
30 10
31 61
32 5
33 297
34 1
35 2
36 5
37 181
38 62
39 298
40 13
41 299
42 136
43 63
44 300
45 301
46 1
47 2
48 182
49 62
50 302
51 3
52 183
53 10
54 137
55 3
56 303
57 1
58 34
59 15
60 62
61 74
62 2
63 138
64 45
65 184
66 185
67 186
68 44
69 21
70 1
71 46
72 1
73 2
74 75
75 26
76 3
77 139
78 31
79 304
80 11
81 305
82 11
83 38
84 32
85 6
86 1
87 2
88 28
89 95
90 6
91 37
92 11
93 306
94 63
95 5
96 307
97 1
98 63
99 14
100 187
101 54
102 35
103 76
104 31
105 308
106 8
107 77
108 1
109 2
110 5
111 181
112 62
113 309
114 64
115 27
116 55
117 76
118 310
119 311
120 1
121 2
122 182
123 62
124 140
125 17
126 10
127 3
128 312
129 141
130 8
131 142
132 1
133 184
134 31
135 13
136 188
137 313
138 189
139 78
140 38
141 314
142 8
143 315
144 0
145 0
146 0
147 0
148 0
149 0
150 0
151 0
152 0
153 0
154 0
155 0
156 0
157 0
158 0
159 0
160 0
161 0
162 0
163 0
164 0
165 0
166 0
167 

257 7
258 75
259 54
260 1
261 14
262 26
263 193
264 10
265 109
266 3
267 57
268 1
269 2
270 30
271 15
272 380
273 18
274 13
275 381
276 1
277 118
278 29
279 207
280 85
281 382
282 1
283 118
284 29
285 207
286 12
287 208
288 11
289 67
290 1
291 383
292 384
293 37
294 385
295 39
296 26
297 8
298 29
299 209
300 69
301 10
302 0
303 0
304 0
305 0
306 0
307 0
308 0
309 0
310 0
311 0
312 0
313 0
314 0
315 0
316 0
317 0
318 0
319 0
320 0
321 0
322 0
323 0
324 0
325 0
326 0
327 0
328 0
329 0
330 0
331 0
332 0
333 0
334 0
335 0
336 0
337 0
338 0
339 0
340 0
341 0
342 0
343 0
344 0
345 0
346 0
347 0
348 0
349 0
350 0
351 0
352 0
353 0
354 0
355 0
356 0
357 0
358 0
359 0
360 0
361 0
362 0
363 0
364 0
365 0
366 0
367 0
368 0
369 0
370 0
371 0
372 0
373 0
374 0
375 0
376 0
377 0
378 0
379 0
380 0
381 0
382 0
383 0
384 0
385 0
386 0
387 0
388 0
389 0
390 0
391 0
392 0
393 0
394 0
395 0
396 0
397 0
398 0
399 0
400 0
401 0
402 0
403 0
404 0
405 0
406 0
407 0
408 0
409 0
410 0
411 0
412 0
413 0
414 0
41

474 0
475 0
476 0
477 0
478 0
479 0
480 0
481 0
482 0
483 0
484 0
485 0
486 0
487 0
488 0
489 0
490 0
491 0
492 0
493 0
494 0
495 0
496 0
497 0
498 0
499 0
500 0
501 0
502 0
503 0
504 0
505 0
506 0
507 0
508 0
509 0
510 0
511 0
512 0
513 0
514 0
515 0
516 0
517 0
518 0
519 0
520 0
521 0
522 0
523 0
524 0
525 0
526 0
527 0
528 0
529 0
530 0
531 0
532 0
533 0
534 0
535 0
536 0
537 0
538 0
539 0
540 0
541 0
542 0
543 0
544 0
545 0
546 0
547 0
548 0
549 0
550 0
10 244
11 1
12 171
13 18
14 3
15 150
16 245
17 172
18 1
19 91
20 126
21 3
22 127
23 128
24 1
25 91
26 126
27 3
28 127
29 128
30 1
31 12
32 480
33 481
34 482
35 3
36 483
37 1
38 484
39 214
40 28
41 112
42 485
43 1
44 486
45 487
46 28
47 3
48 196
49 1
50 3
51 488
52 489
53 2
54 490
55 61
56 1
57 2
58 246
59 491
60 247
61 2
62 70
63 1
64 492
65 493
66 248
67 3
68 494
69 1
70 495
71 14
72 27
73 165
74 104
75 496
76 1
77 27
78 249
79 248
80 497
81 23
82 498
83 1
84 49
85 125
86 3
87 125
88 244
89 1
90 171
91 18
92 3
93 150
94 245
95 172


123 0
124 0
125 0
126 0
127 0
128 0
129 0
130 0
131 0
132 0
133 0
134 0
135 0
136 0
137 0
138 0
139 0
140 0
141 0
142 0
143 0
144 0
145 0
146 0
147 0
148 0
149 0
150 0
151 0
152 0
153 0
154 0
155 0
156 0
157 0
158 0
159 0
160 0
161 0
162 0
163 0
164 0
165 0
166 0
167 0
168 0
169 0
170 0
171 0
172 0
173 0
174 0
175 0
176 0
177 0
178 0
179 0
180 0
181 0
182 0
183 0
184 0
185 0
186 0
187 0
188 0
189 0
190 0
191 0
192 0
193 0
194 0
195 0
196 0
197 0
198 0
199 0
200 0
201 0
202 0
203 0
204 0
205 0
206 0
207 0
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0
250 0
251 0
252 0
253 0
254 0
255 0
256 0
257 0
258 0
259 0
260 0
261 0
262 0
263 0
264 0
265 0
266 0
267 0
268 0
269 0
270 0
271 0
272 0
273 0
274 0
275 0
276 0
277 0
278 0
279 0
280 0
281 0
282 0
283 0
284 0
285 0
286 0
287 0
288 0
289 

152 79
153 1
154 15
155 77
156 3
157 341
158 39
159 342
160 18
161 343
162 2
163 11
164 66
165 33
166 1
167 11
168 24
169 344
170 64
171 80
172 33
173 45
174 11
175 106
176 1
177 11
178 106
179 3
180 345
181 17
182 13
183 346
184 347
185 146
186 1
187 2
188 13
189 348
190 349
191 147
192 147
193 1
194 22
195 107
196 22
197 22
198 1
199 22
200 107
201 22
202 22
203 1
204 22
205 107
206 22
207 22
208 1
209 22
210 107
211 22
212 22
213 1
214 350
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0
250 0
251 0
252 0
253 0
254 0
255 0
256 0
257 0
258 0
259 0
260 0
261 0
262 0
263 0
264 0
265 0
266 0
267 0
268 0
269 0
270 0
271 0
272 0
273 0
274 0
275 0
276 0
277 0
278 0
279 0
280 0
281 0
282 0
283 0
284 0
285 0
286 0
287 0
288 0
289 0
290 0
291 0
292 0
293 0
294 0
295 0
296 0
297 0
298 0
299 0
300 0
301 0
302 0
303 0
304 0
305 0
306 0
3

11 12
12 230
13 7
14 23
15 88
16 1
17 36
18 428
19 80
20 231
21 23
22 164
23 1
24 31
25 429
26 430
27 1
28 12
29 53
30 23
31 232
32 69
33 23
34 431
35 1
36 2
37 90
38 432
39 433
40 3
41 434
42 1
43 10
44 435
45 2
46 436
47 18
48 208
49 1
50 20
51 437
52 13
53 188
54 60
55 7
56 438
57 1
58 439
59 440
60 233
61 12
62 234
63 1
64 18
65 235
66 124
67 61
68 3
69 57
70 1
71 10
72 146
73 8
74 73
75 56
76 140
77 211
78 441
79 1
80 52
81 1
82 36
83 20
84 15
85 165
86 236
87 48
88 112
89 237
90 1
91 17
92 3
93 83
94 15
95 166
96 8
97 32
98 1
99 53
100 8
101 50
102 167
103 1
104 69
105 238
106 239
107 8
108 240
109 18
110 1
111 46
112 1
113 2
114 20
115 15
116 442
117 3
118 443
119 444
120 1
121 12
122 5
123 87
124 168
125 121
126 7
127 162
128 1
129 445
130 39
131 55
132 446
133 8
134 29
135 164
136 1
137 36
138 20
139 78
140 447
141 13
142 448
143 449
144 1
145 2
146 241
147 29
148 450
149 451
150 144
151 1
152 3
153 452
154 453
155 454
156 28
157 13
158 455
159 1
160 456
161 136
162 95
163 28


226 277
227 1
228 8
229 278
230 3
231 279
232 280
233 174
234 1
235 63
236 13
237 281
238 35
239 76
240 31
241 113
242 282
243 1
244 9
245 9
246 9
247 9
248 9
249 9
250 1
251 9
252 9
253 9
254 9
255 9
256 9
257 1
258 9
259 9
260 9
261 9
262 9
263 9
264 1
265 9
266 9
267 9
268 9
269 9
270 0
271 0
272 0
273 0
274 0
275 0
276 0
277 0
278 0
279 0
280 0
281 0
282 0
283 0
284 0
285 0
286 0
287 0
288 0
289 0
290 0
291 0
292 0
293 0
294 0
295 0
296 0
297 0
298 0
299 0
300 0
301 0
302 0
303 0
304 0
305 0
306 0
307 0
308 0
309 0
310 0
311 0
312 0
313 0
314 0
315 0
316 0
317 0
318 0
319 0
320 0
321 0
322 0
323 0
324 0
325 0
326 0
327 0
328 0
329 0
330 0
331 0
332 0
333 0
334 0
335 0
336 0
337 0
338 0
339 0
340 0
341 0
342 0
343 0
344 0
345 0
346 0
347 0
348 0
349 0
350 0
351 0
352 0
353 0
354 0
355 0
356 0
357 0
358 0
359 0
360 0
361 0
362 0
363 0
364 0
365 0
366 0
367 0
368 0
369 0
370 0
371 0
372 0
373 0
374 0
375 0
376 0
377 0
378 0
379 0
380 0
381 0
382 0
383 0
384 0
385 0
386 0
387 0
388 0
3

([array([ 43,   1,  30,   6,  44, 180,   6,  44,   3, 291], dtype=int32),
  array([  1,  30,   6,  44, 180,   6,  44,   3, 291,  17], dtype=int32),
  array([ 30,   6,  44, 180,   6,  44,   3, 291,  17, 292], dtype=int32),
  array([  6,  44, 180,   6,  44,   3, 291,  17, 292, 133], dtype=int32),
  array([ 44, 180,   6,  44,   3, 291,  17, 292, 133,   1], dtype=int32),
  array([180,   6,  44,   3, 291,  17, 292, 133,   1,   2], dtype=int32),
  array([  6,  44,   3, 291,  17, 292, 133,   1,   2,  37], dtype=int32),
  array([ 44,   3, 291,  17, 292, 133,   1,   2,  37,   6], dtype=int32),
  array([  3, 291,  17, 292, 133,   1,   2,  37,   6, 293], dtype=int32),
  array([291,  17, 292, 133,   1,   2,  37,   6, 293,  13], dtype=int32),
  array([ 17, 292, 133,   1,   2,  37,   6, 293,  13, 294], dtype=int32),
  array([292, 133,   1,   2,  37,   6, 293,  13, 294, 295], dtype=int32),
  array([133,   1,   2,  37,   6, 293,  13, 294, 295,  42], dtype=int32),
  array([  1,   2,  37,   6, 293,  13,

In [46]:
nmh_songs = load_data()

In [49]:
find_longest_song(nmh_songs)

551